tag_prefix = "v"
ignore_merge_commits = true
branch_whitelist = ["master", "main"]

pre_bump_hooks = [
    "echo {{version}}",
	"npm --no-git-tag-version -f version v{{version}}",
]
post_bump_hooks = [
    "git push",
    "git push --tags",
#	"gh release create {{version}} -d -t 'Version {{version}}' -n \"$(cog changelog -a v{{version}})\"",
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
cog check -l
pnpm format
"""

[git_hooks.pre-push]
script = """#!/bin/sh
if cog check -l; then
    exit 0
fi

echo "Invalid commits were found, force push with '--no-verify'"
exit 1
"""

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "svelte-starter-kit"
owner = "xmlking"
authors = [{ username = "xmlking", signature = "Sumanth Chinthagunta" }]

[bump_profiles]
