fragment Policy_list_fields on policies {
	id
	# action
	# annotations
	# appId
	createdAt
	# createdBy
	# description
	destinationAddress
	destinationPort
	# direction
	disabled
	displayName
	# protocol
	sourceAddress
	sourcePort
	subjectDisplayName
	# organization
	# subjectId
	# subjectSecondaryId
	# subjectType
	# tags
	template
	updatedAt
	# updatedBy
	# validFrom
	# validTo
	# weight
}
