query SearchPolicies(
	$where: policies_bool_exp
	$limit: Int = 50
	$offset: Int = 0
	$orderBy: [policies_order_by!] = [{ updatedAt: desc_nulls_last }]
) {
	policies(order_by: $orderBy, limit: $limit, offset: $offset, where: $where) {
		# ...Policy_list_fields @mask_disable
		id
		description
		createdAt
		destinationAddress
		destinationPort
		disabled
		displayName
		sourceAddress
		sourcePort
		subjectDisplayName
		template
		updatedAt
	}
}
