query GetPolicy($id: uuid!) {
	policies_by_pk(id: $id) {
		# ...Policy_all_fields @mask_disable
		id
		action
		annotations
		appId
		createdAt
		createdBy
		description
		destinationAddress
		destinationPort
		direction
		disabled
		displayName
		protocol
		sourceAddress
		sourcePort
		subjectDisplayName
		subjectDomain
		subjectId
		subjectSecondaryId
		subjectType
		tags
		template
		updatedAt
		updatedBy
		validFrom
		validTo
		weight
	}
}
