table:
  name: order
  schema: public
object_relationships:
  - name: customer
    using:
      foreign_key_constraint_on: customer_id
insert_permissions:
  - role: editor
    permission:
      check: {}
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
  - role: moderator
    permission:
      check: {}
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
  - role: supervisor
    permission:
      check: {}
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
select_permissions:
  - role: editor
    permission:
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
      filter: {}
      allow_aggregations: true
  - role: moderator
    permission:
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
      filter: {}
      allow_aggregations: true
  - role: supervisor
    permission:
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
      filter: {}
      allow_aggregations: true
  - role: viewer
    permission:
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
      filter: {}
      allow_aggregations: true
update_permissions:
  - role: editor
    permission:
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
      filter: {}
      check: {}
  - role: moderator
    permission:
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
      filter: {}
      check: {}
  - role: supervisor
    permission:
      columns:
        - customer_id
        - id
        - discount_price
        - order_date
        - product
        - purchase_price
        - transaction_id
      filter: {}
      check: {}
delete_permissions:
  - role: editor
    permission:
      filter: {}
  - role: moderator
    permission:
      filter: {}
  - role: supervisor
    permission:
      filter: {}
