table:
  name: customer
  schema: public
array_relationships:
  - name: orders
    using:
      foreign_key_constraint_on:
        column: customer_id
        table:
          name: order
          schema: public
insert_permissions:
  - role: editor
    permission:
      check: {}
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
  - role: moderator
    permission:
      check: {}
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
  - role: supervisor
    permission:
      check: {}
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
select_permissions:
  - role: editor
    permission:
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
      filter: {}
      allow_aggregations: true
  - role: moderator
    permission:
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
      filter: {}
      allow_aggregations: true
  - role: supervisor
    permission:
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
      filter: {}
      allow_aggregations: true
  - role: viewer
    permission:
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
      filter: {}
      allow_aggregations: true
update_permissions:
  - role: editor
    permission:
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
      filter: {}
      check: {}
  - role: moderator
    permission:
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
      filter: {}
      check: {}
  - role: supervisor
    permission:
      columns:
        - id
        - email
        - first_name
        - ip_address
        - last_name
        - phone
        - username
      filter: {}
      check: {}
delete_permissions:
  - role: editor
    permission:
      filter: {}
  - role: moderator
    permission:
      filter: {}
  - role: supervisor
    permission:
      filter: {}
