table:
  name: tz_policies
  schema: public
insert_permissions:
  - role: editor
    permission:
      check:
        _and:
          - created_by:
              _eq: x-hasura-user-id
          - subject_domain:
              _eq: x-hasura-org-id
      set:
        created_by: x-hasura-user-id
        subject_domain: x-hasura-org-id
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
  - role: moderator
    permission:
      check:
        _and:
          - created_by:
              _eq: x-hasura-user-id
          - subject_domain:
              _eq: x-hasura-org-id
      set:
        created_by: x-hasura-user-id
        subject_domain: x-hasura-org-id
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
  - role: supervisor
    permission:
      check: {}
      set:
        created_by: x-hasura-user-id
        subject_domain: x-hasura-org-id
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
select_permissions:
  - role: editor
    permission:
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
      filter:
        subject_domain:
          _eq: x-hasura-org-id
      allow_aggregations: true
  - role: moderator
    permission:
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
      filter:
        subject_domain:
          _eq: x-hasura-org-id
      allow_aggregations: true
  - role: supervisor
    permission:
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
      filter: {}
      allow_aggregations: true
  - role: viewer
    permission:
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
      filter:
        subject_domain:
          _eq: x-hasura-org-id
      allow_aggregations: true
update_permissions:
  - role: editor
    permission:
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
      filter:
        _and:
          - created_by:
              _eq: x-hasura-user-id
          - subject_domain:
              _eq: x-hasura-org-id
      check: {}
      set:
        subject_domain: x-hasura-org-id
        updated_by: x-hasura-user-id
  - role: moderator
    permission:
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
      filter:
        subject_domain:
          _eq: x-hasura-org-id
      check: null
      set:
        subject_domain: x-hasura-org-id
        updated_by: x-hasura-user-id
  - role: supervisor
    permission:
      columns:
        - tags
        - disabled
        - template
        - action
        - app_id
        - created_by
        - description
        - destination_address
        - destination_port
        - direction
        - display_name
        - protocol
        - source_address
        - source_port
        - subject_display_name
        - subject_domain
        - subject_id
        - subject_secondary_id
        - subject_type
        - updated_by
        - weight
        - created_at
        - deleted_at
        - updated_at
        - valid_from
        - valid_to
        - annotations
        - id
      filter: {}
      check: {}
      set:
        subject_domain: x-hasura-org-id
        updated_by: x-hasura-user-id
delete_permissions:
  - role: editor
    permission:
      filter:
        _and:
          - created_by:
              _eq: x-hasura-user-id
          - subject_domain:
              _eq: x-hasura-org-id
  - role: moderator
    permission:
      filter:
        subject_domain:
          _eq: x-hasura-org-id
  - role: supervisor
    permission:
      filter: {}
