table:
  name: action
  schema: public
is_enum: true
select_permissions:
  - role: agent
    permission:
      columns:
        - description
        - value
      filter: {}
  - role: self
    permission:
      columns:
        - description
        - value
      filter: {}
      allow_aggregations: true
  - role: supervisor
    permission:
      columns:
        - description
        - value
      filter: {}
