table:
  name: organization
  schema: public
is_enum: true
select_permissions:
  - role: agent
    permission:
      columns:
        - description
        - value
      filter: {}
  - role: manager
    permission:
      columns:
        - description
        - value
      filter: {}
  - role: user
    permission:
      columns:
        - description
        - value
      filter: {}
